//Chat state
export const DELETE_CHAT = 'DELETE_CHAT'

export const CHATS_LOAD_REQUEST = 'CHATS_LOAD_REQUEST'
export const CHATS_LOAD_SUCCESS = 'CHATS_LOAD_SUCCESS'
export const CHATS_LOAD_ERROR = 'CHATS_LOAD_ERROR'

export const ADD_NEW_MESSAGE_REQUEST = 'ADD_NEW_MESSAGE_REQUEST'
export const ADD_NEW_MESSAGE_SUCCESS = 'ADD_NEW_MESSAGE_SUCCESS'
export const ADD_NEW_MESSAGE_ERROR = 'ADD_NEW_MESSAGE_ERROR'

export const ADD_CHAT_REQUEST = 'ADD_CHAT_REQUEST'
export const ADD_CHAT_SUCCESS = 'ADD_CHAT_SUCCESS'
export const ADD_CHAT_ERROR = 'ADD_CHAT_ERROR'

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST'
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS'
export const DELETE_CHAT_ERROR = 'DELETE_CHAT_ERROR'

export const CHAT_FIRE  = 'CHAT_FIRE'
export const CHAT_UNFIRE  = 'CHAT_UNFIRE'

//Profile state
export const PROFILE_LOAD_REQUEST  = 'PROFILE_LOAD_REQUEST'
export const PROFILE_LOAD_SUCCESS  = 'PROFILE_LOAD_SUCCESS'
export const PROFILE_LOAD_ERROR  = 'PROFILE_LOAD_ERROR'
