export enum ChatsActionTypes  {
	CHATS_LOAD_REQUEST = "CHATS_LOAD_REQUEST",
	CHATS_LOAD_SUCCESS = "CHATS_LOAD_SUCCESS",
	CHATS_LOAD_FAILURE = "CHATS_LOAD_FAILURE",

	ADD_CHAT_REQUEST = "ADD_CHAT_REQUEST",
 	ADD_CHAT_SUCCESS = "ADD_CHAT_SUCCESS",
	ADD_CHAT_FAILURE = "ADD_CHAT_FAILURE",

	CHAT_DELETE = "CHAT_DELETE",

	CHAT_FIRE_REQUEST = "CHAT_FIRE_REQUEST",
	CHAT_FIRE_SUCCESS = "CHAT_FIRE_SUCCESS",
	CHAT_FIRE_FAILURE = "CHAT_FIRE_FAILURE",

	CHAT_UNFIRE_REQUEST = "CHAT_UNFIRE_REQUEST",
	CHAT_UNFIRE_SUCCESS = "CHAT_UNFIRE_SUCCESS",
 	CHAT_UNFIRE_FAILURE = "CHAT_UNFIRE_FAILURE",

 	CLEAR_CHAT = "CLEAR_CHAT",

	MESSAGE_SEND_REQUEST = "MESSAGE_SEND_REQUEST",
 	MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS",
 	MESSAGE_SEND_FAILURE = "MESSAGE_SEND_FAILURE",

 	MESSAGE_DELETE_REQUEST = "MESSAGE_DELETE_REQUEST",
 	MESSAGE_DELETE_SUCCESS = "MESSAGE_DELETE_SUCCESS",
 	MESSAGE_DELETE_FAILURE = "MESSAGE_DELETE_FAILURE",
};

export type ChatDeleteAction = {
	type: ChatsActionTypes.CHAT_DELETE,
	payload: number,
};

export type ClearChatAction = {
	type: ChatsActionTypes.CLEAR_CHAT,
	payload: number,
};