export default {
    UPDATE_WS_CONNECTION_STATUS: 'UPDATE_WS_CONNECTION_STATUS',
    SET_SELECTED_CHAT: 'SET_SELECTED_CHAT',
    OPENED_USER_PROFILE: 'OPENED_USER_PROFILE',
    LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
    SET_COMMON_VIEW_IMAGES: 'SET_COMMON_VIEW_IMAGES',
    SET_ABOUT_PAGE_OPEN: 'SET_ABOUT_PAGE_OPEN',

    SEND_MESSAGE: 'SEND_MESSAGE',

    SET_CHATS: 'SET_CHATS',
    SET_CONTACTS: 'SET_CONTACTS',
    SET_FORWARD_MESSAGE: 'SET_FORWARD_MESSAGE',
    SET_CURRENT_USER: 'SET_CURRENT_USER',

    LOADING: 'LOADING',
    CONTACTS_LOADING: 'CONTACTS_LOADING',
    ERROR: 'ERROR',

    AUTH:'AUTH',
    REGISTER: 'REGISTER',
    UPDATE_USER: 'UPDATE_USER',
    LOAD_CHATS: 'LOAD_CHATS',
    LOAD_CHAT_MESSAGES: 'LOAD_CHAT_MESSAGES',
    LOAD_CONTACTS: 'LOAD_CONTACTS',
    DELETE_CHAT: 'DELETE_CHAT',
};


