export default {
    UPDATE_WS_CONNECTION_STATUS: 'UPDATE_WS_CONNECTION_STATUS',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_SELECTED_CHAT: 'SET_SELECTED_CHAT',
    OPENED_USER_PROFILE: 'OPENED_USER_PROFILE',
    SET_CHATS: 'SET_CHATS',
    SET_CONTACTS: 'SET_CONTACTS'
};


