export enum ChatsActionTypes {
    CHATS_LOAD_REQUEST = 'CHATS_LOAD_REQUEST',
    CHATS_LOAD_SUCCESS = 'CHATS_LOAD_SUCCESS',
    CHATS_LOAD_ERROR = 'CHATS_LOAD_ERROR',

    ADD_NEW_MESSAGE_REQUEST = 'ADD_NEW_MESSAGE_REQUEST',
    ADD_NEW_MESSAGE_SUCCESS = 'ADD_NEW_MESSAGE_SUCCESS',
    ADD_NEW_MESSAGE_ERROR = 'ADD_NEW_MESSAGE_ERROR',

    ADD_CHAT_REQUEST = 'ADD_CHAT_REQUEST',
    ADD_CHAT_SUCCESS = 'ADD_CHAT_SUCCESS',
    ADD_CHAT_ERROR = 'ADD_CHAT_ERROR',

    DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST',
    DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS',
    DELETE_CHAT_ERROR = 'DELETE_CHAT_ERROR',

    CHAT_FIRE  = 'CHAT_FIRE',
    CHAT_UNFIRE  = 'CHAT_UNFIRE'
}

export enum profileActionTypes {
    PROFILE_LOAD_REQUEST  = 'PROFILE_LOAD_REQUEST',
    PROFILE_LOAD_SUCCESS  = 'PROFILE_LOAD_SUCCESS',
    PROFILE_LOAD_ERROR  = 'PROFILE_LOAD_ERROR'
}